SELECT info.ITEM_ID, info.ITEM_NAME, info.RARITY
FROM ITEM_INFO info
WHERE ITEM_ID NOT IN (SELECT PARENT_ITEM_ID 
                FROM ITEM_TREE WHERE NOT ISNULL(PARENT_ITEM_ID))
ORDER BY ITEM_ID DESC;